name: Pre-release Pipeline

on:
  push:
    branches: [ dev ]
    tags: [ 'v*-beta*', 'v*-alpha*', 'v*-rc*' ]

env:
  DOTNET_VERSION: '8.0.413'

jobs:
  build-and-test-prerelease:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Pack prerelease
      run: dotnet pack Flume/Flume.csproj --configuration Release --output ./nupkgs
      
    - name: Publish prerelease to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
    - name: Create GitHub Pre-release
      uses: softprops/action-gh-release@v1
      with:
        files: ./nupkgs/*.nupkg
        generate_release_notes: true
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
