name: Pull Request Checks

on:
  pull_request:
    branches: [ main, dev ]

env:
  DOTNET_VERSION: '8.0.413'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Run code analysis
      run: dotnet build --no-restore --configuration Release /p:RunCodeAnalysis=true
      
    - name: Check for warnings as errors
      run: dotnet build --no-restore --configuration Release /p:TreatWarningsAsErrors=true
